### ISSUE TITLE
containers option not working on firefox

### ISSUE THREAD

**Issue by fawaf** [brcontainer/prevent-duplicate-tabs#13]
for some reason, ignoring duplicate tabs in containers somehow does not work anymore in firefox. it worked when the extenstion was first updated, but clicking/selecting the option and then refreshing the options page shows it as unselected again.

**Comment by brcontainer** [comment]
@fawaf I will check the problem. Grateful.

**Comment by brcontainer** [comment]
@fawaf fixed bug, update for 0.7.3. Thanks!

**Comment by fawaf** [comment]
confirmed fixed.
