### ISSUE TITLE
Installation fails on firefox 52.0

### ISSUE THREAD

**Issue by ewuc** [brcontainer/prevent-duplicate-tabs#15]
I can't install add-on on Firefox 52.0, also can't install on Basilisk browser (updated Firefox)

I receive an error: 
Installation aborted because the add-on appears to be corrupt.
Manually installation by downloading file doesn't work either.

**Comment by brcontainer** [comment]
@ewuc are you installing from https://addons.mozilla.org/firefox/addon/smart-prevent-duplicate-tabs/ in Firefox?

**Comment by brcontainer** [comment]
@ewuc Basilisk uses XUL and don`t supports [WebExtensions](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions), see details in:

- https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Browser_compatibility_for_manifest.json
- https://support.mozilla.org/en-US/kb/frequently-asked-questions-firefox-addon

About Firefox 52, are you installing from https://addons.mozilla.org/firefox/addon/smart-prevent-duplicate-tabs/?

**Comment by brcontainer** [comment]
@ewuc tested on Firefox 52.0, installing:

![installing add-on](https://user-images.githubusercontent.com/4368952/115097292-98108280-9eff-11eb-9033-740c6718d352.png)

Firefox version:

![Firefox about window](https://user-images.githubusercontent.com/4368952/115097295-99da4600-9eff-11eb-9637-d9807922ed3a.png)
