### ISSUE TITLE
Add option to not close tab if it's in another Firefox window

### ISSUE THREAD

**Issue by Oberdiah** [brcontainer/prevent-duplicate-tabs#16]
I frequently have more than one Firefox window open on different desktops, and it's sometimes annoying for a de-duplication to occur when I can't even see the original tab.

Amazing addon by the way, it's a lifesaver :)

**Comment by brcontainer** [comment]
@Oberdiah Great idea, I will make you consider duplicates only from the same window.

**Comment by brcontainer** [comment]
@brcontainer https://github.com/brcontainer/prevent-duplicate-tabs/commit/a9293ee5e3e718a31067be9ffc792c01398a3b12 soon it will be available in "stores".

- [x] [Firefox Add-ons](https://addons.mozilla.org/en/firefox/addon/smart-prevent-duplicate-tabs/)
- [x] [Chrome Extensions](https://chrome.google.com/webstore/detail/prevent-duplicate-tabs/eednccpckdkpojaiemedoejdngappaag)
- [x] [Opera Extensions](https://addons.opera.com/en/extensions/details/prevent-duplicate-tabs/)
- [x] [Microsoft Edge Add-ons](https://microsoftedge.microsoft.com/addons/detail/prevent-duplicate-tabs/iijplllphnkkeepcinimpjobncicbbmb)
