### ISSUE TITLE
Reloads and discards old tabs data

### ISSUE THREAD

**Issue by dezza** [brcontainer/prevent-duplicate-tabs#21]
**Describe the bug**
If you open tab 1 and enter into a form field, then open a duplicate of tab 1 you lose form input in tab 1.

**To Reproduce**
1. Open tab 1, enter form input
2. Open tab 2 with same url
3. Tab 1 form input is cleared, the tab is reloaded

**Expected behavior**
Do not reload.

**Additional context**
Current settings:
Close olders = 0
Keep the tab that is active = 1
Only http = 1
Querystring = 1
Hash = 0
Incognito = 0
Windows = 1
Containers = 1

Events
Start = 0
Update = 0
Create = 1
Replace = 0
Datachange = 0

**Comment by dansteen** [comment]
I have this issue as well.  According to the docs, it's supposed to preserve the existing tab when a new tab is opened and I have the "Close Olders" *not* checked.  Instead it closes the existing tab and opens a new one regardless of what i select for that option.
Thanks!

EDIT:  A bit more poking reveals that it seems like it depends on the age of the tab.  If I let the tab exist for more than ~60 seconds then the new tab will be closed instead.  If the old tab has existed for less than ~60 seconds then the old tab will be closed.

**Comment by brcontainer** [comment]
@dezza @dansteen  thanks for the suggestion, i will keep the progress report in -> https://github.com/brcontainer/prevent-duplicate-tabs/issues/12

I'm working to see the best way to solve this without having to resort to workarounds, as things like that are not part of the native webextensions APIs, so I'll have to inject scripts into the pages (but I want to avoid this path as much as possible, as it will require more user permissions)

**Comment by dansteen** [comment]
Thanks for looking into this @brcontainer!
