### ISSUE TITLE
[Feature] Also avoid duplicated tab when opening URL from command line

### ISSUE THREAD

**Issue by kp-gl** [brcontainer/prevent-duplicate-tabs#24]
I often open tabs by the help of an external tool. it's frustrating that duplicates may occur then.
(same happens when you click repeatedly on a link e.g. in a mail)

It would be great if those duplicates would be avoided, like usually done by the plugin

I tried both config settings to no avail.

**Comment by brcontainer** [comment]
It is impossible, not for the specific extension, but for any extension that manages tabs, the API defines a limited control of how the process of loading a tab occurs, here are the details:

- https://developer.chrome.com/docs/extensions/reference/tabs/#event

I hope you can understand why the extension was idealized and [described](https://github.com/brcontainer/prevent-duplicate-tabs#about) in such a way and that you can find in the _stores of the browsers_ you like an extension that meets your specific needs.

_I appreciate your understanding._
