### ISSUE TITLE
Don't auto-close, but only notify of duplicate tabs

### ISSUE THREAD

**Issue by fischer-felix** [brcontainer/prevent-duplicate-tabs#28]
**Is your feature request related to a problem? Please describe.**
With how I browse the web, there are many times when I want to intentionally have duplicate tabs. However, sometimes like for example when shopping I would like to be notified when I open a product page twice (e.g. when browsing using different filters, some might be there twice)

**Describe the solution you'd like**
I would like, if I was just notified in some way, for example if the two duplicate tabs were highlighted, so I would be able to decide on my own if I wanted to keep both or close one of them.

**Describe alternatives you've considered**
You could also show a pop-up upon opening a duplicate tab, so I could choose if I wanted to open it or not.

**Comment by brcontainer** [comment]
The idea is interesting, but it's not the reason that led me to create the extension, there are already many extensions that do what they want, I needed something that was automatic, for work purposes and even for people who like the extension to self-manage as configured by the user.

About your last order:

> You can also show a popup when opening a duplicate tab, so I can choose whether to open it or not.

It is impossible, not for the specific extension, but for any extension that manages tabs, the API defines a limited control of how the process of loading a tab occurs, here are the details:

- https://developer.chrome.com/docs/extensions/reference/tabs/#event

I hope you can understand why the extension was idealized and [described](https://github.com/brcontainer/prevent-duplicate-tabs#about) in such a way and that you can find in the _stores of the browsers_ you like an extension that meets your specific needs.
