### ISSUE TITLE
[enhancement] many points

### ISSUE THREAD

**Issue by perdolka** [brcontainer/prevent-duplicate-tabs#3]
- [x]  Add **_locale** - for translating.
- [x] Add "**Do nothing**" option - for manual deleting instead automatic.
- [ ] If point 2 is realized, add indicator to an icon (number of duplicates) and/or "sad" icon.
Like this: 
<a href="http://piccy.info/view3/12413509/1315ffd5fbaaff95a7a8bc9055485777/" target="_blank"><img src="http://i.piccy.info/i9/71caa95f02d51279774fe4728009d174/1528983844/2200/1246306/sampl.png" alt="Piccy.info - Free Image Hosting" border="0" /></a><a href="http://i.piccy.info/a3c/2018-06-14-13-44/i9-12413509/40x45-r" target="_blank"><img src="http://i.piccy.info/a3/2018-06-14-13-44/i9-12413509/40x45-r/i.gif" alt="" border="0" /></a>
- [ ] If point 2 is realized, add a list of duplicated tabs to pop-up menu.
- [x] Closable items. Like this: 
<a href="http://piccy.info/view3/12413602/7f3c32a11dfba8431be0149279773e12/orig/" target="_blank"><img src="http://i.piccy.info/i9/94ab94bfed6552904007ecf4f8239c33/1528985141/59891/1246306/ts1_800.jpg" alt="Piccy.info - Free Image Hosting" border="0" /></a><a href="http://i.piccy.info/a3c/2018-06-14-14-05/i9-12413602/800x514-r" target="_blank"><img src="http://i.piccy.info/a3/2018-06-14-14-05/i9-12413602/800x514-r/i.gif" alt="" border="0" /></a>

**Comment by brcontainer** [comment]
I do not know if I agree with the last one, the others I find interesting as being optional, but I hope you understand that the intention of it to be so is to be an automatic practice for experimental and inexperienced users.

The main idea was to be different from the ones that already existed and be simple to use.

But I promise to look carefully at your suggestions :+1:

**Comment by brcontainer** [comment]
Closable items are available in 0.7.9 version, available in:

- https://addons.mozilla.org/firefox/addon/smart-prevent-duplicate-tabs/
- https://chrome.google.com/webstore/detail/prevent-duplicate-tabs/eednccpckdkpojaiemedoejdngappaag

For the Opera store, I'm waiting for a moderator's review.
