### ISSUE TITLE
Close duplicate tab for pinned tabs

### ISSUE THREAD

**Issue by renatocfrancisco** [brcontainer/prevent-duplicate-tabs#30]
Extension doesn't seem to close a duplicate tab when there is a pinned tab with the same url.
In this case, the non pinned tab would be closed. I don't know. It's something I noticed. Maybe you could consider this for a feature request.

![chrome_g6SjtlPWci](https://user-images.githubusercontent.com/56325092/231208912-4df6de82-33e1-4c79-bd67-4845f6af3d34.png)

<details>
<summary markdown="span">Other example</summary>

![chrome_U2Zm7rcOER](https://user-images.githubusercontent.com/56325092/231211638-b78b057b-d833-41ea-b228-346f982fc6a0.gif)

```

</details>

**Comment by brcontainer** [comment]
Yes, because pinned guides are disregarded in the check, precisely because pinned guides are more important. New tabs that are repeated from a pinned tab will not be compared, they are in separate contexts, precisely because of their importance.

Suggestions are most welcome.
