### ISSUE TITLE
better hast or querystring filter

### ISSUE THREAD

**Issue by salihkurtdereli** [brcontainer/prevent-duplicate-tabs#35]
**Is your feature request related to a problem? Please describe.**
When I want to close the duplicate websites for "Indeed" it is not working since all the clone tabs hast different queries in their links. I will give you 2 different links for the same job position and as you can see the way I found the pages (after the part "&" ) totaly different For example : 
"
`https://example?jk=8bbb5ab99313287f&q=%22data+scientist%22+OR+%22data+engineer%22+OR+%22data+analyst%22+OR+%22analyst%22+OR+%22data+science%22&l=Deutschland&tk=1h5tdbrt4jv5d800&from=web&advn=903448295031421&adid=415354387&ad=-6NYlbfkN0C0wj5AXSXvlSTZ_ElArzG3rzKm092HTC4At3lyVzSrhWGiCyNWu67UbZ-7XV4vTWDxS0vCuESffQILSfaDZg6JNJKx-AlJb6Rbau2pE1fVCEH5IgOzJ2v1C45iMVS1I8V_mwQOnGzh2ZZ1QDQWA6Q4jkNGKdoeaRs9GHMM0KWyPpsF1Hxe6XkpAsEr_kuxi8P-x7HdU4wUNgkwTsbtaAcq9Uno_pg8hsXn0KS26xzlQHW0TOJPgr9RdziyHn-5NL_oU3V_0mCHsflYfNygXSBzMZqMSsJEaTnXm5NbOW6E6aEXWGfJ3N4Nmjs5zPHqNJSMYT7_wsTzsE0OVTjOPdfwsloEnwQ7-hGcjuY_zgmmyJvy4bWHnPAa9QV88DRF_FWla10es8HIWIWP9AeGY8bMxjgxfIE0RYhPjamf4jtPTIDfZgIIPV_U7UTOvgy5Nz4%3D&sjdu=MFsPULTKcOzfqqFX7JzpsxnRdyVaTKwgjHkalYzNxaiNk4aeLK7IG9BG27aQjXFd0fhwWN4Gi50gTV4sho_oRRO7I_fU4g4TeRjfvFQ7yAVvzhYSUTUmEH7lWwIlN6uds04O-AvRovZSdISXsK53bpMHWSF6ZIdO2XWdFB2w7h9OnltpKHX1MJn5EEkz42Gonr5eVskS4lUPp179L39ZQchXAj4XudL8nIqDbA7LsGhBs8G6vgjduWYCkkoDKYT6UcQ4XgcSJ1ixFFEOb1hI8MaiPrkoXVEEO8phi4Mp-tzLjE4WWf8Wbiyy8B4B_GzA8-zbs6lTJtkNLAE6rMiucHra7qGl-LENawHZM_JaGMkyYtT0s46ud3uu-TimO1RS6sNI2bKRembaY5vFNw3K2Q&acatk=1h5tdcd0visu1800&pub=4a1b367933fd867b19b072952f68dceb&xkcb=SoAU-_M3N9SgWNx_lJ0CbzkdCdPP&vjs=3`

`https://example?jk=8bbb5ab99313287f&q=%22data+science%22&l=Deutschland&tk=1h5tdbbahkcoh801&from=web&advn=903448295031421&adid=415354387&ad=-6NYlbfkN0C0wj5AXSXvlSTZ_ElArzG3rzKm092HTC4At3lyVzSrhWGiCyNWu67UbZ-7XV4vTWDxS0vCuESffQILSfaDZg6JNJKx-AlJb6Rbau2pE1fVCEH5IgOzJ2v1C45iMVS1I8V_mwQOnGzh2ZZ1QDQWA6Q4ZQQmBFNcKYW6R3NO6qt3O7FxRs4SNQqTnwyQiB8UD6Dp3zITe9A0TUr7olaXRP5i7lF48EBNz8KEUeBsczgdOxBtDzI7aLm5hDf7GgnZoPVI_mBpytSvhnt0MqCZ8ME_sa_hVii6eviW1O0BJiEscD36Er8xtySDMLkt3BBqBo2-cyVaAXTsIolbzn_sbNbE4pSr8JjdPdW-0Bsj_87SXGwG4UeTW2IpcPwxa9MxBMgEd1JKJFcsS2AwTlESxSWVvuP0zqrAPyibzXkzyXdLAxEy416sHkz5HwD_cx8fHqU%3D&sjdu=MFsPULTKcOzfqqFX7JzpsxnRdyVaTKwgjHkalYzNxaiNk4aeLK7IG9BG27aQjXFd0fhwWN4Gi50gTV4sho_oRRO7I_fU4g4TeRjfvFQ7yAVvzhYSUTUmEH7lWwIlN6uds04O-AvRovZSdISXsK53bpMHWSF6ZIdO2XWdFB2w7h9OnltpKHX1MJn5EEkz42Gonr5eVskS4lUPp179L39ZQchXAj4XudL8nIqDbA7LsGhBs8G6vgjduWYCkkoDKYT6UcQ4XgcSJ1ixFFEOb1hI8MaiPrkoXVEEO8phi4Mp-tzLjE4WWf8Wbiyy8B4B_GzA8-zbs6lTJtkNLAE6rMiucHra7qGl-LENawHZM_JaGMkyYtT0s46ud3uu-TimO1RS6sNI2bKRembaY5vFNw3K2Q&acatk=1h5tdiocvjttr802&pub=4a1b367933fd867b19b072952f68dceb&xkcb=SoAA-_M3N9SitPWMNh0IbzkdCdPP&vjs=3`

**Describe the solution you'd like**

extension should have a feature to delete the part after "&" character than compare. In that way the extension will find more clones. and will be more helpful.

**Describe alternatives you've considered**

you can put the content  of the page to a hash function (specific part or all) then you can show possible clone tabs to close. but there should be option as close the tabs manually.

**Additional context**

better apps easier world ! Good luck :*

**Comment by brcontainer** [comment]
Thanks for the sugestion.

It has already been suggested, we will follow in the issue: https://github.com/brcontainer/prevent-duplicate-tabs/issues/26
