### ISSUE TITLE
Pls make it available on mobile

### ISSUE THREAD

**Issue by x3oo** [brcontainer/prevent-duplicate-tabs#39]
### Describe the solution you'd like

as stated

### Will the API support this feature?

- [X] I agree

**Comment by brcontainer** [comment]
Which browser and system? Firefox for Android does not allow addons except those chosen by them.

**Comment by x3oo** [comment]
ah damn

Am Sa., 17. Feb. 2024 um 15:39 Uhr schrieb Guilherme Nascimento <
***@***.***>:
