### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by mjo** [brcontainer/prevent-duplicate-tabs#4]
Can you elaborate more settings?
Sort order

    Close olders

    Closes the old tabs (enabled or disabled if the tab is active it will keep)

    Prefer tab activated

    Keeping tab that is activated (visible)

What those mean to the end user? Either I don't understand or those are not functioning. If launching some URL out of the Firefox in Windows OS multiple times, I don't see any change of behavior while changing those  above settings. Version number is 0.5.0

Other than that, great add-on thank you!

**Comment by brcontainer** [comment]
I agree that the descriptions should be improved. I will see what it is possible to do. Thanks :)

**Comment by brcontainer** [comment]
@mjo See new descriptions https://github.com/brcontainer/prevent-duplicate-tabs#configs

- Available for [Chrome](https://chrome.google.com/webstore/detail/prevent-duplicate-tabs/eednccpckdkpojaiemedoejdngappaag)
- Available for [Firefox](https://addons.mozilla.org/en-US/firefox/addon/smart-prevent-duplicate-tabs/)
- Available [MS Edge (chromium)](https://microsoftedge.microsoft.com/addons/detail/iijplllphnkkeepcinimpjobncicbbmb)
- Add-on for Opera is NOT available, but available for Opera Next and Opera Developer
