### ISSUE TITLE
I want to contribute

### ISSUE THREAD

**Issue by rpgdev** [brcontainer/prevent-duplicate-tabs#45]
### Related to a problem?

Is there a tutorial somewhere I can read to get started? I'm fine with js but I've never touched browser addons before. It'd be great if there was a development section on the README so we can get some pointers.

### Describe the solution you'd like

A contributors section on the README

### Describe alternatives you've considered

Reading the code

### Will the API support this feature?

- [X] I agree

**Comment by brcontainer** [comment]
@rpgdev Get started:

* https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions
* https://developer.chrome.com/docs/extensions/get-started
