### ISSUE TITLE
Settings not persistent

### ISSUE THREAD

**Issue by blaise-io** [brcontainer/prevent-duplicate-tabs#6]
When I change a setting in the toolbar button menu, close the settings, then reopen settings, all settings are back to default. I'm on Firefox 76.

**Comment by brcontainer** [comment]
> 
> 
> When I change a setting in the toolbar button menu, close the settings, then reopen settings, all settings are back to default. I'm on Firefox 76.

Thanks, fixing the problem

**Comment by brcontainer** [comment]
@blaise-io fixed bugs: https://github.com/brcontainer/prevent-duplicate-tabs/commit/7900829825846dc92954730133b43a2ca12bd9a3

- Available for [Chrome](https://chrome.google.com/webstore/detail/prevent-duplicate-tabs/eednccpckdkpojaiemedoejdngappaag)
- Available for [Firefox](https://addons.mozilla.org/en-US/firefox/addon/smart-prevent-duplicate-tabs/)
- Available [MS Edge (chromium)](https://microsoftedge.microsoft.com/addons/detail/iijplllphnkkeepcinimpjobncicbbmb)
- Add-on for Opera is NOT available, but available for Opera Next and Opera Developer
